services:
  - type: web
    name: rifas-backend
    env: node
    plan: free
    buildCommand: npm ci && npx prisma generate
    startCommand: npm run migrate && npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
